# Generated by Django 5.2.4 on 2025-08-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reservation_total_cost_reservation_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', '상담중'), ('CONFIRMED', '예약확정'), ('PAID', '잔금완료'), ('COMPLETED', '여행완료'), ('CANCELED', '취소')], default='PENDING', max_length=10),
        ),
    ]
