# Generated by Django 5.2.4 on 2025-08-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='category',
            field=models.CharField(choices=[('PACKAGE', '패키지 여행'), ('FLIGHT', '항공권'), ('HOTEL', '호텔')], default='PACKAGE', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tour_name',
            field=models.CharField(max_length=200, verbose_name='대표명(상품명/항공편/호텔명)'),
        ),
    ]
