# Generated by Django 5.2.4 on 2025-08-06 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reservation_category_reservation_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='requests',
            field=models.TextField(blank=True, verbose_name='요청사항'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='category',
            field=models.CharField(choices=[('TOUR', '투어'), ('RENTAL_CAR', '렌터카'), ('ACCOMMODATION', '숙박'), ('GOLF', '골프'), ('TICKET', '티켓'), ('OTHER', '기타')], default='TOUR', max_length=20, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='details',
            field=models.JSONField(blank=True, default=dict, verbose_name='카테고리별 상세정보'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='대표 종료일'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='내부 메모'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='대표 시작일'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', '상담중'), ('CONFIRMED', '예약확정'), ('PAID', '잔금완료'), ('COMPLETED', '여행완료'), ('CANCELED', '취소')], default='PENDING', max_length=10, verbose_name='예약상태'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='원가'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='판매가'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='tour_name',
            field=models.CharField(max_length=200, verbose_name='대표명'),
        ),
    ]
