# Generated by Django 5.2.4 on 2025-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_reservation_requests_alter_reservation_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='업체명')),
                ('category', models.CharField(choices=[('HOTEL', '호텔'), ('AIRLINE', '항공사'), ('RENTAL', '렌터카'), ('RESTAURANT', '식당'), ('AGENCY', '현지 에이전시'), ('OTHER', '기타')], max_length=20, verbose_name='업체 종류')),
                ('contact_person', models.CharField(blank=True, max_length=50, verbose_name='담당자')),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
            ],
        ),
    ]
