# Generated by Django 5.2.4 on 2025-08-08 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(verbose_name='거래일')),
                ('transaction_type', models.CharField(choices=[('INCOME', '수입'), ('EXPENSE', '지출')], max_length=10, verbose_name='거래 종류')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='금액')),
                ('description', models.CharField(max_length=255, verbose_name='내용')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.partner', verbose_name='관련 제휴업체')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reservation', verbose_name='관련 예약')),
            ],
        ),
    ]
