# Generated by Django 5.2.4 on 2025-08-11 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense_item',
            field=models.CharField(blank=True, choices=[('RENTAL_CAR', '렌터카'), ('ACCOMMODATION', '숙박'), ('GOLF', '골프'), ('CASH', '시제'), ('DEPOSIT', '예약금'), ('PARTNER', '제휴업체'), ('TICKET', '티켓'), ('TRANSPORT', '교통비'), ('MISC', '잡비'), ('GUIDE', '가이드'), ('OTHER', '기타')], max_length=20, null=True, verbose_name='지출항목'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CARD', '카드'), ('CASH', '현금'), ('TRANSFER', '계좌이체')], max_length=10, null=True, verbose_name='결제방법'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', '처리중'), ('COMPLETED', '완료'), ('HOLD', '보류')], default='PENDING', max_length=10, verbose_name='처리현황'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
