# Generated by Django 5.2.4 on 2025-08-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_transaction_expense_item_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expense_item',
            field=models.CharField(blank=True, choices=[('RENTAL_CAR', '렌터카'), ('ACCOMMODATION', '숙박'), ('GOLF', '골프'), ('CASH', '시제'), ('DEPOSIT', '예약금'), ('PURCHASE', '매입'), ('PARTNER', '제휴업체'), ('TICKET', '티켓'), ('GUIDE', '가이드'), ('MISC', '잡비'), ('OTHER', '기타')], max_length=20, null=True, verbose_name='지출항목'),
        ),
    ]
