# Generated by Django 5.2.4 on 2025-08-13 06:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='결제금액'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', '미결제'), ('DEPOSIT', '예약금 입금'), ('PAID', '결제완료')], default='UNPAID', max_length=20, verbose_name='결제 현황'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_notes',
            field=models.TextField(blank=True, verbose_name='특이사항'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='예약일'),
        ),
    ]
